"""A scoped two-paper comparison with retrieval, evidence store and review.

Cached PDFs are fetched separately; full papers are not redistributed in Git.
Default extraction is a transparent rule policy. Optional model role outputs
are checked against saved evidence and kept even when malformed.
"""
import argparse
import asyncio
from dataclasses import asdict
import hashlib
import json
from pathlib import Path
import re
from urllib.request import Request,urlopen
from .planning import Plan,Task
from .providers import parse_object,ProviderError

FIXTURES=Path(__file__).resolve().parents[2]/'fixtures'


def fetch_papers(directory):
    directory=Path(directory);directory.mkdir(parents=True,exist_ok=True)
    manifest=json.loads((FIXTURES/'papers.json').read_text(encoding="utf-8"));result=[]
    for paper in manifest:
        target=directory/(paper['id']+'.pdf')
        if not target.exists():
            with urlopen(Request(paper['url'],headers={'User-Agent':'TheBestAIGuide teaching research'}),timeout=40) as response:raw=response.read(12_000_001)
            if len(raw)>12_000_000 or not raw.startswith(b'%PDF'):raise ValueError('invalid or oversized PDF')
            target.write_bytes(raw)
        result.append({**paper,'sha256':hashlib.sha256(target.read_bytes()).hexdigest()})
    return result


def extract(paper,directory):
    from .documents import parse_pdf
    path=Path(directory)/(paper['id']+'.pdf')
    if not path.exists():return {'id':paper['id'],'status':'missing','url':paper['url']}
    pages=parse_pdf(path)
    for page in pages:
        normalized=' '.join(page['text'].split());match=re.search(re.escape(paper['needle']),normalized,re.I)
        if match:
            # A small locator, <=12 words, not a redistributed abstract.
            quote=' '.join(normalized[match.start():].split()[:12])
            return {'id':paper['id'],'status':'found','url':paper['url'],'version':paper['version'],
                    'page':page['page'],'sha256':page['sha256'],'quote':quote,'axis':paper['axis'],
                    'author_summary':paper['summary'],'summary_provenance':'authored reading note; not generated by keyword matching'}
    return {'id':paper['id'],'status':'not_found','url':paper['url']}


async def compare(directory, *, mode='multi', provider=None):
    papers=json.loads((FIXTURES/'papers.json').read_text(encoding="utf-8"));calls=[]
    async def plan(_):return {'question':'Do Transformer attention and LoRA solve the same problem?',
                              'axes':['architecture','adaptation'],'sources':[p['id'] for p in papers]}
    def worker(paper):
        async def run(_):
            evidence=await asyncio.to_thread(extract,paper,directory)
            if provider and evidence['status']=='found':
                reply=provider.complete([{'role':'system','content':'You are an evidence reader. Return JSON {"source_id":"id","quote":"copy exact supplied quote","missing":"what this short evidence cannot establish"}. Do not invent performance comparisons.'},
                    {'role':'user','content':json.dumps(evidence)}],json_mode=True)
                calls.append(asdict(reply))
                try:
                    role=parse_object(reply.text)
                    valid=role.get('source_id')==evidence['id'] and role.get('quote')==evidence['quote']
                except ProviderError:role={'raw':reply.text};valid=False
                evidence={**evidence,'model_reading':role,'model_citation_valid':valid}
            return evidence
        return run
    async def writer(inputs):
        rows=list(inputs.values());missing=[e['id'] for e in rows if e['status']!='found']
        result={'rows':rows,'missing_sources':missing,'comparable_quality_metrics':False,
                'conclusion':None if missing else 'The compared notes concern architecture and adaptation; these methods are compatible. The supplied evidence does not establish a performance ranking.',
                'conclusion_provenance':'authored comparison rule over labelled reading notes'}
        if provider:
            reply=provider.complete([{'role':'system','content':'Compare the supplied reading notes. Return JSON {"conclusion":"short","source_ids":["id"],"limits":"short"}. Never rank speed or quality without matched measurements.'},
                                    {'role':'user','content':json.dumps(rows)}],json_mode=True)
            calls.append(asdict(reply))
            try:result['model_comparison']=parse_object(reply.text)
            except ProviderError:result['model_comparison']={'invalid':reply.text}
        return result
    async def review(inputs):
        report=inputs['writer'];found=[e for e in report['rows'] if e['status']=='found']
        return {'all_sources_present':not report['missing_sources'],'evidence_locations_valid':all(e.get('page',0)>0 and e.get('sha256') for e in found),
                'unsupported_metric_ranking':report['comparable_quality_metrics'],
                'boundary':'Location and schema checks are not an independent semantic review; inspect the supplied reading notes and paper pages.'}
    if mode=='single':
        planning=await plan({});rows={p['id']:await worker(p)({'planner':planning}) for p in papers}
        report=await writer(rows);reviewed=await review({'writer':report})
        trace=[{'role':'single','input':planning,'outputs':rows},{'role':'writer','output':report},{'role':'reviewer','output':reviewed}]
    else:
        tasks=[Task('planner',(),plan)]+[Task(p['id'],('planner',),worker(p)) for p in papers]
        tasks +=[Task('writer',tuple(p['id'] for p in papers),writer),Task('reviewer',('writer',),review)]
        dag=Plan(tasks,concurrency=2,timeout=300);result=await dag.execute();report=result['writer'];reviewed=result['reviewer'];trace=dag.trace
    return {'mode':mode,'policy':'real model role calls with fixed decomposition' if provider else 'deterministic role workflow',
            'report':report,'review':reviewed,'trace':trace,'model_calls':calls,'call_count':len(calls),
            'boundary':'No inference that multiple roles improve accuracy; compare the same inputs and retain failures.'}


def render(result):
    lines=['# 两篇论文的范围比较','','| 材料 | 讨论层次 | 定位 | 阅读笔记 |','| --- | --- | --- | --- |']
    for row in result['report']['rows']:
        lines.append(f"| {row['id']} | {row.get('axis','缺失')} | {row.get('url','')}，p.{row.get('page','?')} | {row.get('author_summary','缺少资料，不作结论')} |")
    lines+=['',result['report']['conclusion'] or '证据不足，停止比较。','','阅读笔记由作者编写；定位脚本只验证短引文与页码。模型读法（若启用）见 JSON trace。']
    return '\n'.join(lines)+'\n'


if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--papers',required=True);p.add_argument('--output',required=True);p.add_argument('--fetch',action='store_true');p.add_argument('--provider',choices=['api','local']);p.add_argument('--model');p.add_argument('--revision');a=p.parse_args()
    if a.fetch:fetch_papers(a.papers)
    provider=None
    if a.provider=='api':
        from .providers import ChatAPI
        provider=ChatAPI.from_env()
    elif a.provider=='local':
        from .providers import LocalChat
        provider=LocalChat(a.model,revision=a.revision)
    output=Path(a.output);output.mkdir(parents=True,exist_ok=True)
    for mode in ['single','multi']:
        result=asyncio.run(compare(a.papers,mode=mode,provider=provider))
        (output/(mode+'.json')).write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n', encoding="utf-8")
        (output/(mode+'.md')).write_text(render(result), encoding="utf-8")
    print(output)
